



version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    restart: unless-stopped
